package sample.spring.mvc.db;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    long countByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    int deleteByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    int insert(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    int insertSelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    List<Sample> selectByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    int updateByExampleSelective(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    int updateByExample(@Param("record") Sample record, @Param("example") SampleExample example);

	String findName(@Param("id") int id);

	@Select("SELECT name FROM sample WHERE id = #{id}")
	String getName(int id);
}