package sample.spring.mvc.db;

public class Sample {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.id
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.name
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample.room
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    private String room;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.id
     *
     * @return the value of sample.id
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.id
     *
     * @param id the value for sample.id
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.name
     *
     * @return the value of sample.name
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.name
     *
     * @param name the value for sample.name
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample.room
     *
     * @return the value of sample.room
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample.room
     *
     * @param room the value for sample.room
     *
     * @mbg.generated Sun Oct 13 20:04:58 JST 2019
     */
    public void setRoom(String room) {
        this.room = room;
    }
}